-- MIGRATION SCRIPT FROM 1.0 TO 2

-- POS drop obsolete fields and indexes 

DROP INDEX POS_IDX02 ON POS;
DROP INDEX POS_IDX03 ON POS;
DROP INDEX POS_IDX04 ON POS;

ALTER TABLE POS
	DROP COLUMN IS_OWN_OFFICE,
	DROP COLUMN IS_DELIVERY_SERVICE_AVAILABLE,
	DROP COLUMN IS_PICKUP_AVAILABLE,
	DROP COLUMN GEO_LATITUDE,
	DROP COLUMN GEO_LONGITUDE;

/*
 * VERSION TABLE
 */
DROP TABLE EURASIA_VER_1_0;
CREATE TABLE EURASIA_VER_2 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
